---
title: "Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(ggpubr)
library(GGally)
library(rpart)
library(rpart.plot)  
library(rattle)
library(randomForest)
library(gbm)
library(ggmosaic)
library(patchwork)
library(MASS)
library(nnet)
library(class)
```





```{r, warning=FALSE, message=FALSE}
## we don't need this block if we use the newest data in block "newdata"
dat=read.csv(file = 'data.csv',encoding="UTF-8")
head(dat)
summary(dat)
str(dat)
dat$category=as.factor(dat$category)
dat$timePeriod=as.factor(dat$timePeriod)
dat$definition=as.factor(dat$definition)
dat$caption=as.factor(dat$caption)
dat$madeForKids=as.factor(dat$madeForKids)
dat$views=log(as.numeric(dat$views))
dat$likes=log(as.numeric(dat$likes))
dat$comments=log(as.numeric(dat$comments)+1)
summary(dat)
time1 = strptime(dat$duration,'PT%MM%SS')
index=which(is.na(time1))
dat$duration[index]
time2 <- strptime(dat$duration,'PT%HH%MM%SS')
time3 <- strptime(dat$duration,'PT%MM')
time4 <- strptime(dat$duration,'PT%SS')
time5 <- strptime(dat$duration,'PT%HH%SS')

time=time1
time[index]=time2[index]
index=which(is.na(time))
time[index]=time3[index]
index=which(is.na(time))
time[index]=time4[index]
index=which(is.na(time))
time[index]=time5[index]
dat$duration=time

dat$duration=difftime(dat$duration,Sys.Date(),units='secs')-14400

for (i in 1:ncol(dat)) {
  print(which(is.na(dat[,i])))
}

dat=na.omit(dat)

dat1=dat
dat1$duration=as.numeric(dat1$duration)



```




## Analysis


```{r}

## we don't need this block if we use the newest data in block "newdata"

dat1$viewsQuartile3 <- ntile(dat1$views, 3)
dat1$likesQuartile3 <- ntile(dat1$likes, 3)
dat1$commentsQuartile3 <- ntile(dat1$comments, 3)


dat1 <- dat1 %>% group_by(viewsQuartile3) %>% mutate(likesQuartile9 = ntile(likes, 3)) %>% ungroup() 
dat1 <- dat1 %>% group_by(viewsQuartile3) %>% mutate(commentsQuartile9 = ntile(comments, 3)) %>% ungroup() 

dat1$likesQuartile9 = (dat1$viewsQuartile3-1)*3+dat1$likesQuartile9
dat1$commentsQuartile9 = (dat1$viewsQuartile3-1)*3+dat1$commentsQuartile9

dat1$viewsQuartile3=as.factor(dat1$viewsQuartile3)
dat1$likesQuartile9=as.factor(dat1$likesQuartile9)
dat1$commentsQuartile9=as.factor(dat1$commentsQuartile9)
```


```{r newdata}
## use the data with age
dat1=read.csv(file = 'datawithlevel9.csv',encoding="UTF-8")
dat1$age=log(dat1$age)
dat1$category=as.factor(dat1$category)
dat1$timePeriod=as.factor(dat1$timePeriod)
dat1$definition=as.factor(dat1$definition)
dat1$caption=as.factor(dat1$caption)
dat1$madeForKids=as.factor(dat1$madeForKids)
dat1$viewsQuartile3=as.factor(dat1$viewsQuartile3)
dat1$likesQuartile9=as.factor(dat1$likesQuartile9)
dat1$commentsQuartile9=as.factor(dat1$commentsQuartile9)
```


```{r}
set.seed(1)
data <- dat1[, c(5,6,8:23)] %>% mutate(id=row_number())
train <- data %>% group_by(viewsQuartile3) %>% sample_frac(0.8) %>% ungroup() 
test <- anti_join(data, train, by = 'id')
# remove the column id
train <- dplyr::select(train, -id)
test <- dplyr::select(test, -id)
```

### LDA

```{r}
# Fit the model
LdaModelForViews = lda(viewsQuartile3 ~ category + timePeriod + definition + caption + madeForKids + duration+age, data = train)
# Make predictions for trainset
LdaPredictionsTrainViews <- LdaModelForViews %>% predict(train)
ldatabletrain=table(predicted=LdaPredictionsTrainViews$class, actual=train$viewsQuartile3)
ldatabletrain
cat("Train prediction error:", mean(LdaPredictionsTrainViews$class!=train$viewsQuartile3))
## separately
cat("Train prediction error for low views:", 1-ldatabletrain[1,1]/sum(ldatabletrain[,1]))
cat("Train prediction error for medium views:", 1-ldatabletrain[2,2]/sum(ldatabletrain[,2]))
cat("Train prediction error for high views:", 1-ldatabletrain[3,3]/sum(ldatabletrain[,3]))

# Make predictions for testset
LdaPredictionsTestViews <- LdaModelForViews %>% predict(test)
ldatabletest=table(predicted=LdaPredictionsTestViews$class, actual=test$viewsQuartile3)
ldatabletest
# Model accuracy for test set
cat("Test prediction error:", mean(LdaPredictionsTestViews$class!=test$viewsQuartile3))

cat("Test prediction error for low views:", 1-ldatabletest[1,1]/sum(ldatabletest[,1]))
cat("Test prediction error for medium views:", 1-ldatabletest[2,2]/sum(ldatabletest[,2]))
cat("Test prediction error for high views:", 1-ldatabletest[3,3]/sum(ldatabletest[,3]))

# likes9

LdaModelForlikes = lda(likesQuartile9 ~ category + timePeriod + definition + caption + madeForKids + duration+age, data = train)
# Make predictions for trainset
LdaPredictionsTrainlikes <- LdaModelForlikes %>% predict(train)
table(predicted=LdaPredictionsTrainlikes$class, actual=train$likesQuartile9)
cat("Train prediction error:", mean(LdaPredictionsTrainlikes$class!=train$likesQuartile9))
# Make predictions for testset
LdaPredictionsTestlikes <- LdaModelForlikes %>% predict(test)
table(predicted=LdaPredictionsTestlikes$class, actual=test$likesQuartile9)
# Model accuracy for test set
cat("Test prediction error:", mean(LdaPredictionsTestlikes$class!=test$likesQuartile9))



# comments9
LdaModelForcomments = lda(commentsQuartile9 ~ category + timePeriod + definition + caption + madeForKids + duration+age, data = train)
# Make predictions for trainset
LdaPredictionsTraincomments <- LdaModelForcomments %>% predict(train)
table(predicted=LdaPredictionsTraincomments$class, actual=train$commentsQuartile9)
cat("Train prediction error:", mean(LdaPredictionsTraincomments$class!=train$commentsQuartile9))
# Make predictions for testset
LdaPredictionsTestcomments <- LdaModelForcomments %>% predict(test)
table(predicted=LdaPredictionsTestcomments$class, actual=test$commentsQuartile9)
# Model accuracy for test set
cat("Test prediction error:", mean(LdaPredictionsTestcomments$class!=test$commentsQuartile9))



```

## plots of LDA

```{r}
true <- data.frame(ld1=LdaPredictionsTestViews$x[,1], class=test$viewsQuartile3)
trueplot = ggplot(data = true) + 
    geom_histogram(mapping = aes(x = ld1, fill = class)) + 
    ggtitle('True')

ldaproj <- data.frame(ld1=LdaPredictionsTestViews$x[,1], class=LdaPredictionsTestViews$class)
ldaplot = ggplot(data = ldaproj) + 
    geom_histogram(mapping = aes(x = ld1, fill = class)) + 
    ggtitle('LDA')
ggarrange(trueplot, ldaplot, ncol=2)

# likes
true <- data.frame(ld1=LdaPredictionsTestlikes$x[,1], class=test$likesQuartile9)
trueplot = ggplot(data = true) + 
    geom_histogram(mapping = aes(x = ld1, fill = class)) + 
    ggtitle('True')

ldaproj <- data.frame(ld1=LdaPredictionsTestlikes$x[,1], class=LdaPredictionsTestlikes$class)
ldaplot = ggplot(data = ldaproj) + 
    geom_histogram(mapping = aes(x = ld1, fill = class)) + 
    ggtitle('LDA')
ggarrange(trueplot, ldaplot, ncol=2)
# comments
true <- data.frame(ld1=LdaPredictionsTestcomments$x[,1], class=test$commentsQuartile9)
trueplot = ggplot(data = true) + 
    geom_histogram(mapping = aes(x = ld1, fill = class)) + 
    ggtitle('True')

ldaproj <- data.frame(ld1=LdaPredictionsTestcomments$x[,1], class=LdaPredictionsTestcomments$class)
ldaplot = ggplot(data = ldaproj) + 
    geom_histogram(mapping = aes(x = ld1, fill = class)) + 
    ggtitle('LDA')
ggarrange(trueplot, ldaplot, ncol=2)
```



### QDA

Seems that we can't apply QDA on our data, the error is: Error in qda.default(x, grouping, ...) : rank deficiency in group 1

```{r}

# Fit the model
#QdaModelForViews = qda(viewsQuartile3 ~ category + timePeriod + definition + caption + madeForKids + duration+age, data = train)
# Make predictions for trainset
#QdaPredictionsTrainViews <- QdaModelForViews %>% predict(train)
#table(predicted=QdaPredictionsTrainViews$class, actual=train$viewsQuartile3)
#cat("Train prediction error:", mean(QdaPredictionsTrainViews$class!=train$viewsQuartile3))
# Make predictions for testset
#QdaPredictionsTestViews <- QdaModelForViews %>% predict(test)
#table(predicted=QdaPredictionsTestViews$class, actual=test$viewsQuartile3)
# Model accuracy for test set
#cat("Test prediction error:", mean(QdaPredictionsTestViews$class!=test$viewsQuartile3))


```


### Multinomial

```{r}
LRModelForViews <- multinom(viewsQuartile3 ~ category + timePeriod + definition + caption + madeForKids + duration+age, data = train, probabilities = TRUE, model = TRUE)
LRPredictionsTestViews  <-  predict(LRModelForViews, test)
tabletest=table(predicted=LRPredictionsTestViews, actual=test$viewsQuartile3)
cat("Test prediction error:", mean(LRPredictionsTestViews!=test$viewsQuartile3))


cat("Test prediction error for low views:", 1-tabletest[1,1]/sum(tabletest[,1]))
cat("Test prediction error for medium views:", 1-tabletest[2,2]/sum(tabletest[,2]))
cat("Test prediction error for high views:", 1-tabletest[3,3]/sum(tabletest[,3]))


LRModelForlikes <- multinom(likesQuartile9 ~ category + timePeriod + definition + caption + madeForKids + duration+age, data = train, probabilities = TRUE, model = TRUE)
LRPredictionsTestlikes  <-  predict(LRModelForlikes, test)
table(predicted=LRPredictionsTestlikes, actual=test$likesQuartile9)
cat("Test prediction error:", mean(LRPredictionsTestlikes!=test$likesQuartile9))

LRModelForcomments <- multinom(commentsQuartile9 ~ category + timePeriod + definition + caption + madeForKids + duration+age, data = train, probabilities = TRUE, model = TRUE)
LRPredictionsTestcomments  <-  predict(LRModelForcomments, test)
table(predicted=LRPredictionsTestcomments, actual=test$commentsQuartile9)
cat("Test prediction error:", mean(LRPredictionsTestcomments!=test$commentsQuartile9))

## train


LRModelForViews <- multinom(viewsQuartile3 ~ category + timePeriod + definition + caption + madeForKids + duration+age, data = train, probabilities = TRUE, model = TRUE)
LRPredictionstrainViews  <-  predict(LRModelForViews, train)
tabletrain=table(predicted=LRPredictionstrainViews, actual=train$viewsQuartile3)
cat("train prediction error:", mean(LRPredictionstrainViews!=train$viewsQuartile3))


cat("train prediction error for low views:", 1-tabletrain[1,1]/sum(tabletrain[,1]))
cat("train prediction error for medium views:", 1-tabletrain[2,2]/sum(tabletrain[,2]))
cat("train prediction error for high views:", 1-tabletrain[3,3]/sum(tabletrain[,3]))


LRModelForlikes <- multinom(likesQuartile9 ~ category + timePeriod + definition + caption + madeForKids + duration+age, data = train, probabilities = TRUE, model = TRUE)
LRPredictionstrainlikes  <-  predict(LRModelForlikes, train)
table(predicted=LRPredictionstrainlikes, actual=train$likesQuartile9)
cat("train prediction error:", mean(LRPredictionstrainlikes!=train$likesQuartile9))

LRModelForcomments <- multinom(commentsQuartile9 ~ category + timePeriod + definition + caption + madeForKids + duration+age, data = train, probabilities = TRUE, model = TRUE)
LRPredictionstraincomments  <-  predict(LRModelForcomments, train)
table(predicted=LRPredictionstraincomments, actual=train$commentsQuartile9)
cat("train prediction error:", mean(LRPredictionstraincomments!=train$commentsQuartile9))
```


## KNN


```{r}

train_ = train
train_$category=as.numeric(train_$category)
train_$timePeriod=as.numeric(train_$timePeriod)
train_$duration=as.numeric(train_$duration)
train_$definition=as.numeric(train_$definition)
train_$caption=as.numeric(train_$caption)
train_$madeForKids=as.numeric(train_$madeForKids)

test_ = test
test_$category=as.numeric(test_$category)
test_$timePeriod=as.numeric(test_$timePeriod)
test_$duration=as.numeric(test_$duration)
test_$definition=as.numeric(test_$definition)
test_$caption=as.numeric(test_$caption)
test_$madeForKids=as.numeric(test_$madeForKids)

trainViews_y = train_ %>% .$viewsQuartile3 
trainViews_x <- train_ %>% dplyr::select('category', 'timePeriod', 'duration', 'definition', 'caption', 'madeForKids','age')

testViews_y = test_ %>% .$viewsQuartile3 
testViews_x = test_ %>% dplyr::select('category', 'timePeriod', "duration", "definition", "caption", "madeForKids",'age')
mean_train = colMeans(trainViews_x)
std_train = sqrt(diag(var(trainViews_x)))
# training data
trainViews_x = scale(trainViews_x, center = mean_train, scale = std_train)
# test data
testViews_x = scale(testViews_x, center = mean_train, scale = std_train)

# We can see when k>50, the error is increasing, so we don't need k>50
k_range = 2:50


train_error = c()
test_error = c()
for(i in 1:length(k_range)){
  pred_train <- knn(trainViews_x, 
                      trainViews_x, 
                      trainViews_y,
                      k = k_range[i])
  train_error[i] = mean(pred_train != trainViews_y)
  pred_test = knn(trainViews_x, 
                      testViews_x, 
                      trainViews_y,
                      k = k_range[i])
  test_error[i] = mean(pred_test != testViews_y)
}
errors = data.frame(train_error, test_error, k_range)
ggplot(errors, aes(x = 1/k_range)) + 
  geom_line(aes(y = train_error, col = "train error"), size=1) + geom_point(aes(y = train_error, col = "train error")) +
  geom_line(aes(y = test_error, col = "test error")) + geom_point(aes(y = test_error, col = "test error")) +
  ylab("Error Rate") + xlab("1/K") + ggtitle("Training and test error rate for KNN") + theme_minimal() +
  scale_color_manual(values = c("train error" = "red", "test error" = "blue"))


ggplot(errors, aes(x = k_range)) + 
  geom_line(aes(y = train_error, col = "train error"), size=1) + geom_point(aes(y = train_error, col = "train error")) +
  geom_line(aes(y = test_error, col = "test error")) + geom_point(aes(y = test_error, col = "test error")) +
  ylab("Error Rate") + xlab("K") + ggtitle("Training and test error rate for KNN") + theme_minimal() +
  scale_color_manual(values = c("train error" = "red", "test error" = "blue"))
```

## LOOCV and knn

```{r}
crossvalidated_error = numeric(49)
for(i in 2:50){
K<-knn.cv(trainViews_x, cl=trainViews_y, k=i)
crossvalidated_error[i-1] = mean(trainViews_y!=K)
}

plot(crossvalidated_error, ty="l", lwd=2, col="blue", xlab="K", ylab ="LOOCV error")

which(crossvalidated_error==min(crossvalidated_error))

errors[which(crossvalidated_error==min(crossvalidated_error)),]

```




## Tree and Random Forest

```{r}
tree = rpart(viewsQuartile3 ~ category+ timePeriod+ definition+ caption+ madeForKids+ + duration+age, data = train, method = "class")
printcp(tree)
plotcp(tree)
prp(tree,type=4,extra=1,clip.right.labs = F)

train.pred=predict(tree, train, type="class")
sum(train.pred != train$viewsQuartile3) / dim(train)[1]
test.pred=predict(tree, test, type="class")
sum(test.pred != test$viewsQuartile3) / dim(test)[1]
table(test.pred, test$viewsQuartile3)


set.seed(2)
test_err = rep(0,27)
dim(test_err)=c(3,3,3)

# m is mtry, n is ntree, o is nodesize
for (m in 3:5) {
  for (n in c(1000,2000,3000)) {
    for (o in 1:3) {
      rf=randomForest(viewsQuartile3 ~ category+ timePeriod+ definition+ caption+ madeForKids+ + duration+age, data = train, mtry=m, ntree=n, nodesize = o)

test_pred <- predict(rf, newdata = test)
err <- mean(test_pred!=test$viewsQuartile3)
test_err[m-2,n/1000,o] = err
}
}
}

test_err
## we can see [2,3,1] has the lowest error, which is m=4, n = 3000, o=1.

rf=randomForest(viewsQuartile3 ~ category+ timePeriod+ definition+ caption+ madeForKids+ duration+age, data = train, mtry=4, ntree=3000, nodesize = 1)
## we can see train error for each level in rf
rf
importance(rf,type=2)

test_pred <- predict(rf, newdata = test)
mean(test_pred!=test$viewsQuartile3)
tabletest=table(test_pred, test$viewsQuartile3)

cat("Test prediction error for low views:", 1-tabletest[1,1]/sum(tabletest[,1]))
cat("Test prediction error for medium views:", 1-tabletest[2,2]/sum(tabletest[,2]))
cat("Test prediction error for high views:", 1-tabletest[3,3]/sum(tabletest[,3]))




```



